name: handover-project
static_sites:
  - name: website
    environment_slug: html
    source_dir: /
    build_command: npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
